### ISSUE TITLE
Upgrade QA tools

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/credential#27]
On [the road to 1.0](https://github.com/ericelliott/credential/issues/26).

See the scripts in [prod-module-boilerplate](https://github.com/ericelliott/prod-module-boilerplate/blob/master/package.json) for reference.
- [x] Upgrade build process and tools
- [x] Verify Travis build
- [x] Replace Mout with native tools or lodash
- [x] Upgrade outdated dependencies
- [ ] Double check pre-commit hook

**Comment by ericelliott** [comment]
Great! I've added some more tasks based on the build feedback.

**Comment by ericelliott** [comment]
:clap:

**Comment by snlacks** [comment]
Ok, I commits/PR'ed what I could. I didn't check-off double check pre-commit hooks or merge because I am not sure what that means.

1. Pre-commit we run validate, which runs lint, builds (sets envs, check runs webpack), and then runs npm test. This is successful on Linux, and runs on Windows if I add the word SET (should probably be an issue)
2. Travis-CI shows it is successful.

**Comment by ericelliott** [comment]
Closing all stale issues and PRs. Please update, ensure all tests pass, and reopen if you really want this in.
