### ISSUE TITLE
Verifying with a pre-parsed JSON object

### ISSUE THREAD

**Issue by matto1990** [ericelliott/credential#46]
When attempting to `verify` a hash I started off by passing in the hash as a Javascript Object. After looking at the code of `verify`, it seems that it always attempts to run `JSON.parse` on the input hash, which in my case was not needed. The solution was to use `JSON.stringify` on the object before passing it to `verify`.

In my case I am using a Postgres JSON column in my database and Knex and Bookshelf as an ORM, which means by the time I receive the password hash from the database it has already been parsed. Ideally I'd be able to pass this directly to `verify` and avoid the step back to a string.

Thanks for the great library!

**Comment by tjconcept** [comment]
Whatever is returned from `hash` is supposed to go unmodified into `verify` again.

The fact that `hash` returns a JSON string is an implementation detail, is not documented, and could change without triggering a new major release. That's why you should not parse it and not store it as anything else than an opaque value.

If you really want to, you should parse it on one side (after `hash`) and stringify it on the other (before `verify`).

**Comment by matto1990** [comment]
Ah OK. That makes sense. From the description of `hash` it says explicitly that it returns a JSON object, so I thought it would be stable. I'll change my database schema to simply accept a string.

Thanks for the quick reply!

**Comment by tjconcept** [comment]
You're right, and I might be over-idealistic about it but unless you have some really good reason to, I'd not run the risk.

I'll close this for now, but feel free to follow up, I'll answer or reopen if necessary :)

**Comment by matto1990** [comment]
No problem at all, I can see the reasoning for it, and I'll hever used the password hash JSON directly, so it makes no difference to me.

It might be worth making this recommendation in the readme though, just in case.
