### ISSUE TITLE
Do not encourage people to write security issue in public places

### ISSUE THREAD

**Issue by Neograph734** [ericelliott/credential#79]
From the [NPM page](https://www.npmjs.com/package/credential): 

> If you find a security flaw in this code, please **report it.**

I did not find an exploit, but I was wondering where the link would lead to, and now I am here.

Just writing the exploits here is not really secure and could in fact risk every use of your module out there, Please consider handling security issues in a closed issue queue or mail or something. Some place where others cannot easily see them.

**Comment by ericelliott** [comment]
I think the risk of failure to patch due to reports falling through the crack of an alternate process (additional reporting friction, side-band for bug reports) outweighs the risk of reporting in GitHub.

See also the warning in the README. Users of this library have already opted into the risks of using a library like this (or any other credential management library) rather than outsourcing credential management (my recommendation for most apps) or developing a solution in-house with a dedicated security team (my recommendation for companies with dedicated security experts, frequent red-team drills, and bug bounty programs).
