### ISSUE TITLE
the 'verify' function takes too much time, about 1.3 seconds

### ISSUE THREAD

**Issue by changchengqin** [ericelliott/credential#84]
the 'verify' function takes too much time, about 1.3 seconds

**Comment by ericelliott** [comment]
In general, the computational work is intentional. That's what supplies security against password crackers. If your system can't handle it in reasonable time, either use a faster system for verification or delegate authorization to a service like Google Firebase or Auth0.

Degrading the work time to make it faster would be irresponsible.

There [is an open issue](https://github.com/ericelliott/credential/issues/83) which may have a positive impact on performance. You're welcome to contribute to it if the suggestions help.
